boxes=2

warehouse.ENGINE=0
warehouse.WHEEL=4
warehouse.BRAKE=2

supplier.interval.ms=200
supplier.cycles=10
supplier.batch.ENGINE=1
supplier.batch.WHEEL=4
supplier.batch.BRAKE=2

car.1.name=Car-A
car.1.repair.ms=500
car.1.order=ENGINE:1,WHEEL:4

car.2.name=Car-B
car.2.repair.ms=400
car.2.order=BRAKE:2,WHEEL:4
